FROM ubuntu:16.04
RUN mkdir /nommem && apt-get update && apt-get install -y gfortran unzip cpanminus
RUN apt-get install -y apt-utils build-essential autoconf automake
RUN cpanm Math::Random Moose MooseX::Params::Validate Statistics::Distributions \
          Archive::Zip File::Copy::Recursive YAML::XS Storable

COPY NONMEM7.4.3.zip /nonmem/NONMEM7.4.3.zip
COPY PsN-4.8.1.tar.gz /nonmem/PsN-4.8.1.tar.gz

WORKDIR /nonmem

RUN unzip -P zorx7bqRT NONMEM7.4.3.zip && tar -xvf PsN-4.8.1.tar.gz
RUN /bin/bash ./nm743CD/SETUP74 ${PWD}/nm743CD /nonmem/nm743 gfortran y /usr/bin/ar same rec q

COPY setup.pl /nonmem/PsN-Source/setup.pl

WORKDIR /nonmem/PsN-Source/

RUN perl setup.pl

WORKDIR /nonmem/nm743
#COPY license/nonmem.lic /nonmem/nm743/license/nonmem.lic

CMD [ "bash" ]